# Numpy Tutorial

In [57]:
import numpy as np

In [3]:
myarr1 = np.array([3,4,6,33])

In [4]:
myarr1

array([ 3,  4,  6, 33])

In [5]:
myarr2 = np.array([3,4,6,33333333333])

In [6]:
myarr2.dtype

dtype('int64')

**1D and 2D arrays**

In [7]:
myarr3 = np.array([5,10,20,30]) #1D array

In [8]:
myarr3

array([ 5, 10, 20, 30])

In [9]:
myarr3.shape

(4,)

In [10]:
myarr3.ndim #to define dimension

1

In [11]:
myarr4 = np.array([[1,3,5,6],[5,10,20,21],[6,8,10,34]]) #2D array

In [12]:
myarr4

array([[ 1,  3,  5,  6],
       [ 5, 10, 20, 21],
       [ 6,  8, 10, 34]])

In [13]:
myarr4.shape

(3, 4)

In [14]:
myarr4.ndim  #to define dimension

2

In [15]:
myarr4.size

12

In [16]:
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [17]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
x.sum(axis=0) #for sum of axis 0 or rows

array([15, 18, 21, 24])

In [19]:
x.sum(axis=1) #for sum of axis 1 or columns

array([10, 26, 42])

In [20]:
x.T #transpose

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [21]:
for items in x:
    print(items)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [22]:
x.size

12

In [23]:
x.ndim

2

In [24]:
x.nbytes

48

In [25]:
oneD = np.array([1,3,4,634,2])

In [26]:
oneD.argmax()

3

In [27]:
oneD.argmin()

0

In [28]:
oneD.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [29]:
oneD.sort()

In [30]:
oneD

array([  1,   2,   3,   4, 634])

In [31]:
y = np.array([[1,2,3,],[5,6,7],[9,4,8]])

In [32]:
y

array([[1, 2, 3],
       [5, 6, 7],
       [9, 4, 8]])

**argmax and argmin**

In [33]:
y.argmax()

6

In [34]:
y.argmin()

0

In [35]:
y.argmax(axis=0)

array([2, 1, 2], dtype=int64)

In [36]:
y.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [37]:
y.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [38]:
y.argmin(axis=1)

array([0, 0, 1], dtype=int64)

In [39]:
y.shape

(3, 3)

In [40]:
y.reshape(9,1) #to reshape

array([[1],
       [2],
       [3],
       [5],
       [6],
       [7],
       [9],
       [4],
       [8]])

**Mathematical operations in numpy**

In [41]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [42]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
arr2 = np.array([[11,12,13],[14,15,16],[17,18,19]])

In [44]:
arr2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [45]:
arr1+arr2 #for add

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [46]:
arr1*arr2 #for mul

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [47]:
np.sqrt(arr1) #for square root

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [48]:
arr1.max()

9

In [49]:
arr1.min()

1

In [50]:
arr2.max()

19

In [51]:
arr2.min()

11

In [52]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
np.where(arr1>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [54]:
type(np.where(arr1>5))

tuple

In [55]:
arr1[1,2] = 0

In [56]:
arr1

array([[1, 2, 3],
       [4, 5, 0],
       [7, 8, 9]])